#http://localhost:5172
@dotnet_primer_HostAddress = https://csc360-backend.azurewebsites.net

GET {{dotnet_primer_HostAddress}}/weatherforecast/
Accept: application/json
###

GET {{dotnet_primer_HostAddress}}/recipes/
Accept: text/plain
###

GET {{dotnet_primer_HostAddress}}/recipeTitles/
Accept: application/json
###

GET {{dotnet_primer_HostAddress}}/recipeIngredients/{repcipeTitle}?recipeTitle=Creamy%20Mashed%20potatoes'
Accept: application/json
